### ISSUE TITLE
"Info" call-out?

### ISSUE THREAD

**Issue by jonathanconway** [AusDTO/gov-au-ui-kit#218]
I noticed we have a "warning" themed callout with red colouring.

Could we also have an "info" call-out, in a more "calming" colour (e.g. turquoise)?

A scenario for this has come up in Identity, specifically, when the user goes to update their details and we want to "call out" that the change will need to be verified:

![screen shot 2016-07-28 at 10 59 50 am](https://cloud.githubusercontent.com/assets/310330/17197704/7c788b22-54b2-11e6-8cd4-d798c30a6c61.png)

**Comment by klepas** [comment]
@jonathanconway Sure. (:

This is easy to do, just low priority for us given the impending deadlines. Might add in my spare time later this week.

**Comment by jonathanconway** [comment]
Sure no rush 😁

**Comment by TrebBrennan** [comment]
FYI early design draft from GovAU/alpha I imagine we will end up heading towards this.
It seems to accommodate most validation types, @jonathanconway is there anything else we should consider?

<img width="619" alt="screen shot 2016-07-29 at 9 33 01 am" src="https://cloud.githubusercontent.com/assets/15899197/17294385/dad90824-5839-11e6-96eb-741b708dd4bb.png">

**Comment by klepas** [comment]
@TrebBrennan I mentioned these to Alz yesterday, and I’m keen to work on these with her if we get the chance to. (:

**Comment by jonathanconway** [comment]
Hey Treb,

Thanks for including me here!

Would be great to do usability & accessibility testing with validation / form interactions as soon as possible.

It might also be good to see these mocked up within a complete form, just to have visual context and see how it sits along-side other components. For example, where will it sit in relation to the field label? (I assume below).

Don’t get me wrong, this looks excellent. Love the line that visually ties the message to the relevant field.

**Comment by klepas** [comment]
Tracked under `DESIGN-218`.

**Comment by klepas** [comment]
Just an update—

We’ve added this as part of 3 new ones to UI-Kit:
1. `callout--info`
2. `callout--error`
3. `callout--success`

These new ones were added in this PR: https://github.com/AusDTO/gov-au-ui-kit/pull/449

The HTML for the example was added in https://github.com/AusDTO/gov-au-ui-kit/pull/452

I note this since they’re actually missing from the design guide/documentation website (ticket for that work: https://github.com/AusDTO/dto-design-guide/issues/119)

Closing this issue subsequently.
