### ISSUE TITLE
Horizontal top-level nav/header styling

### ISSUE THREAD

**Issue by ltankey** [AusDTO/gov-au-ui-kit#45]
Seems the latest release has removed the default header div.wrapper styling. Taking a look at the documentation, there doesn't seem to be anything specifically for this (although it does exist in the styling of the thing itself as `section.govau--header` and `section.hero`.

Is this the semantic markup for these elements, and there's just no docs for it? Or is this something that is likely to change?

Cheers

![image](https://cloud.githubusercontent.com/assets/5369670/16248966/16a5e22c-3856-11e6-89cc-b84c71339c77.png)

**Comment by klepas** [comment]
Hey @ltankey.

This should be the markup from hereon in; if it changes from here we’ll make notes about in the release notes.

If you copy that general markup you’ll be fine — most importantly:
- use the `banner` and `contentinfo` ARIA roles for the page `header` and `footer` respectively — we target these two page items via their ARIA roles rather than their class or position
- b/c we need to escape the grid, and get full 100% viewport width, we’re using that `div.wrapper` class, inside the `header`; inside those are then the different banner sections of the header.

Lemme know if that makes sense?

I agree we should be documenting this more verbosely somewhere upon release.

**Comment by ltankey** [comment]
Thanks @klepas 

I've implemented it as per the UI-kit markup although it would be great to include in the KSS.

I'm not quite clear on your comments RE: ARIA roles vs classes - do you have a sample bit of markup to clear this up for me?

Cheers

**Comment by klepas** [comment]
@ltankey:

```
  <header role="banner">
    <section class="controls">
      <div class="wrapper">
        <a href="#" class="login">Logout</a>
      </div>
    </section>
    <section class="govau--header">
      <div class="wrapper">
        <div class="govau--logo">
          <a href="#" class="logo">gov.au</a> <span class="badge--alpha">alpha</span>
        </div>
        <div class="feedback">
          <a href="#" class="button--feedback">Give feedback</a>
        </div>
      </div>
    </section>
    <section class="hero">
      <div class="wrapper">
        <a href="#" class="site-title">Department of Intertubes</a>
        <p class="tagline">Calibration of intertube serialisation will be a real game-changer.</p>
      </div>
    </section>
  </header>
```

Same for the page footer—

```
    <footer role="contentinfo">
      <div class="wrapper">
        [...]
      </div>
    </footer>
```

**Comment by ltankey** [comment]
Ahh gotchya - have implemented in the same way, so that's great :+1:

Thanks
