### ISSUE TITLE
Incorrect colour for light aqua

### ISSUE THREAD

**Issue by Jane24** [AusDTO/gov-au-ui-kit#463]
Bug - Incorrect colour displayed for light aqua on this page:
http://gov-au-ui-kit.apps.staging.digital.gov.au/section-colours.html
It's not #5BCBE3
Should be #def4f9

**Comment by klepas** [comment]
Thanks for reporting this.

We’ve moved over to the new version of the documentation for the codebase — http://guides.service.gov.au/design-guide/ — where we actually had basically the same error (`$lighter-aqua` had the wrong hex value).

Fixed in: https://github.com/AusDTO/dto-design-guide/pull/126

**Comment by Jane24** [comment]
Ah sorry. Still had the old version bookmarked.

**Comment by klepas** [comment]
All good — still ended up being a bug that had made it’s way over to the new docs, so much appreciated. (:
